# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_Q_inplace <- function(x) {
    invisible(.Call(`_MLRClust_qr_Q_inplace`, x))
}

rsample <- function(A, p) {
    .Call(`_MLRClust_rsample`, A, p)
}

rsample_sym <- function(A, p, use_lower = TRUE) {
    .Call(`_MLRClust_rsample_sym`, A, p, use_lower)
}

sparse_matrix_coords <- function(mat, nthread = 1L) {
    .Call(`_MLRClust_sparse_matrix_coords`, mat, nthread)
}

krylov_space_part <- function(coords, P, scale = 1.0, q = 1L, nthread = 1L) {
    .Call(`_MLRClust_krylov_space_part`, coords, P, scale, q, nthread)
}

